<?xml version="1.0" encoding="utf-8"?><Database Name="TestAngularDb" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreationTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AssignedEmployeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AppEmployee_Task" Member="AppEmployee" ThisKey="AssignedEmployeeId" OtherKey="Id" Type="AppEmployee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppEmployees" Member="AppEmployees">
    <Type Name="AppEmployee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="CreationTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="AppEmployee_Task" Member="Tasks" ThisKey="Id" OtherKey="AssignedEmployeeId" Type="Task" />
    </Type>
  </Table>
</Database>